//Issues
export const SET_ISSUES = 'SET_ISSUES';
export const SET_ISSUES_FAIL = 'SET_ISSUES_FAIL';

export const POST_ISSUE = 'POST_ISSUE';
export const POST_ISSUE_SUCCESS = 'POST_ISSUE_SUCCESS';
export const POST_ISSUE_FAIL = 'POST_ISSUE_FAIL';

export const DELETE_ISSUE = 'DELETE_ISSUE';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAIL = 'DELETE_ISSUE_FAIL';

export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
export const UPDATE_ISSUE_FAIL = 'UPDATE_ISSUE_FAIL';

// Auth
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User
export const INIT_USER = 'INIT_USER';
export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS';
export const INIT_USER_FAIL = 'INIT_USER_FAIL';
